#!/bin/sh
# can't trust the return code, apparently

filename=`readlink -f $0`
dirname=`dirname "$filename"`

output=`java -jar /usr/share/java/js.jar "$dirname/rhino.js" "$dirname/jslint.js" $@`
echo "$output"
exit=0

for arg in $@
do
	if [[ -e "$arg" && ! "$output" =~ "jslint: No problems found in $arg" ]]; then
		exit=1
	fi
done

exit $exit
